### ISSUE TITLE
the visible url needs to be tinyurl.com/usufslc

### ISSUE THREAD

**Issue by llamapope** [USUFSLC/website#4]
https://github.com/USUFSLC/website/blob/0da4d8ccd9d5b945ecca3b63dff737d130302cab/index.html#L34

**Comment by llamapope** [comment]
shows as tinyrul.com/usufslc which probably has malware - update images too

**Comment by jacstrong** [comment]
Thanks for the feedback! We love people!

Just FYI this issue was related to another issue, in the future check those and comment on those if they're related instead of creating a new one.
